// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: users.proto

package com.sirius.twitter;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sirius.twitter.Empty)
    com.google.protobuf.MessageOrBuilder {
}
