// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: users.proto

package com.sirius.twitter;

public final class Users {
  private Users() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sirius_twitter_UserById_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sirius_twitter_UserById_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sirius_twitter_UserByDni_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sirius_twitter_UserByDni_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sirius_twitter_UserByName_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sirius_twitter_UserByName_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sirius_twitter_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sirius_twitter_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sirius_twitter_UserDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sirius_twitter_UserDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sirius_twitter_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sirius_twitter_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sirius_twitter_UsersList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sirius_twitter_UsersList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013users.proto\022\022com.sirius.twitter\"\026\n\010Use" +
      "rById\022\n\n\002id\030\001 \001(\005\"\030\n\tUserByDni\022\013\n\003dni\030\001 " +
      "\001(\005\"\032\n\nUserByName\022\014\n\004name\030\001 \001(\t\"\007\n\005Empty" +
      "\"C\n\007UserDto\022\013\n\003dni\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\r" +
      "\n\005email\030\003 \001(\t\022\016\n\006active\030\004 \001(\010\"L\n\004User\022\n\n" +
      "\002id\030\001 \001(\005\022\013\n\003dni\030\002 \001(\005\022\014\n\004name\030\003 \001(\t\022\r\n\005" +
      "email\030\004 \001(\t\022\016\n\006active\030\005 \001(\010\"3\n\tUsersList" +
      "\022&\n\004user\030\001 \003(\0132\030.com.sirius.twitter.User" +
      "2\314\004\n\014UsersService\022D\n\010findById\022\034.com.siri" +
      "us.twitter.UserById\032\030.com.sirius.twitter" +
      ".User\"\000\022F\n\tfindByDni\022\035.com.sirius.twitte" +
      "r.UserByDni\032\030.com.sirius.twitter.User\"\000\022" +
      "H\n\nfindByName\022\036.com.sirius.twitter.UserB" +
      "yName\032\030.com.sirius.twitter.User\"\000\022E\n\007fin" +
      "dAll\022\031.com.sirius.twitter.Empty\032\035.com.si" +
      "rius.twitter.UsersList\"\000\022E\n\ncreateUser\022\033" +
      ".com.sirius.twitter.UserDto\032\030.com.sirius" +
      ".twitter.User\"\000\022B\n\nupdateUser\022\030.com.siri" +
      "us.twitter.User\032\030.com.sirius.twitter.Use" +
      "r\"\000\022J\n\016deactivateUser\022\034.com.sirius.twitt" +
      "er.UserById\032\030.com.sirius.twitter.User\"\000\022" +
      "F\n\ndeleteUser\022\034.com.sirius.twitter.UserB" +
      "yId\032\030.com.sirius.twitter.User\"\000B\026\n\022com.s" +
      "irius.twitterP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_sirius_twitter_UserById_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_sirius_twitter_UserById_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sirius_twitter_UserById_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_sirius_twitter_UserByDni_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_sirius_twitter_UserByDni_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sirius_twitter_UserByDni_descriptor,
        new java.lang.String[] { "Dni", });
    internal_static_com_sirius_twitter_UserByName_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_sirius_twitter_UserByName_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sirius_twitter_UserByName_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_sirius_twitter_Empty_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_sirius_twitter_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sirius_twitter_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_com_sirius_twitter_UserDto_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_sirius_twitter_UserDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sirius_twitter_UserDto_descriptor,
        new java.lang.String[] { "Dni", "Name", "Email", "Active", });
    internal_static_com_sirius_twitter_User_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_sirius_twitter_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sirius_twitter_User_descriptor,
        new java.lang.String[] { "Id", "Dni", "Name", "Email", "Active", });
    internal_static_com_sirius_twitter_UsersList_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_sirius_twitter_UsersList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sirius_twitter_UsersList_descriptor,
        new java.lang.String[] { "User", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
