// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: users.proto

package com.sirius.twitter;

public interface UserByNameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sirius.twitter.UserByName)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
