// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: users.proto

package com.sirius.twitter;

public interface UserByIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sirius.twitter.UserById)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
