version: "3.7"

services:
  db:
    container_name: db_container
    image: postgres
    networks:
      - pilot-project-network
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: test_db
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 54321:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}

networks:
  pilot-project-network:
