// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: users.proto

package grpc;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:users.Empty)
    com.google.protobuf.MessageOrBuilder {
}
