// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: users.proto

package grpc;

public interface UserByIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:users.UserById)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
