// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: users.proto

package grpc;

public interface UsersListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:users.UsersList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .users.User user = 1;</code>
   */
  java.util.List<grpc.User> 
      getUserList();
  /**
   * <code>repeated .users.User user = 1;</code>
   */
  grpc.User getUser(int index);
  /**
   * <code>repeated .users.User user = 1;</code>
   */
  int getUserCount();
  /**
   * <code>repeated .users.User user = 1;</code>
   */
  java.util.List<? extends grpc.UserOrBuilder> 
      getUserOrBuilderList();
  /**
   * <code>repeated .users.User user = 1;</code>
   */
  grpc.UserOrBuilder getUserOrBuilder(
      int index);
}
