// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: users.proto

package grpc;

public interface UserByDniOrBuilder extends
    // @@protoc_insertion_point(interface_extends:users.UserByDni)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 dni = 1;</code>
   * @return The dni.
   */
  int getDni();
}
