// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: users.proto

package grpc;

public interface UserDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:users.UserDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 dni = 1;</code>
   * @return The dni.
   */
  int getDni();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>bool active = 4;</code>
   * @return The active.
   */
  boolean getActive();
}
